### ISSUE TITLE
Conflict with format prop and SVG format attribute

### ISSUE THREAD

**Issue by joaogranado** [ameyms/react-animated-number#1]
With new support for SVG elements, added on _react 15.0.0_, `format` attribute is considered by the renderer a valid HTML attribute, resulting in the element being rendered with the content of the format prop, which in this case it is the raw output of the function being passed.

``` html
<div format="function format(value) {
  return format;
}">
```

I would suggest to remove `format` (and consequently every other unnecessary prop) from the `props` passed to `React.createElement` on `render` method. This could be easily accomplished on the destructuring assignment:

``` js
const { component, format, value, frameStyle, stepPrecision, ...rest } = this.props;

// ...

return React.createElement(
  component,
  { ...rest, style },
  format(adjustedValue)
);
```

Although this is a quick fix,  I would suggest to rename `format` to something like `formatValue`, but it is up to you, since would lead to a breaking change. IMHO it would be a better solution in order to avoid conflicts with SVG's `format` attribute (considering the fact that this component supports SVG).

**Comment by nunorafaelrocha** [comment]
Agree with renaming to `formatValue`.

**Comment by ameyms** [comment]
I agree. I will rename it to `formatValue`. PRs also welcome.
