### ISSUE TITLE
Don't error on null value

### ISSUE THREAD

**Issue by thaithcock** [ameyms/react-animated-number#12]
Hi,

The component throws a prop error if you pass null (which is the same as not passing the value), but actually it handles it perfectly (it animates downward to 0 and then displays nothing).

In this case, you would use a formatter to handle the display value. I imagine using a formatter is not foreign to people using this component.

The way it works is perfect (for my usage), except that it throws an error.

Thoughts?

**Comment by itscarlosrufo** [comment]
I just created #17 PR - [Fix request] Proposal for remove value prop warning to fix this issue.
