### ISSUE TITLE
Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the undefined component.

### ISSUE THREAD

**Issue by demobo-com** [ameyms/react-animated-number#2]
Adding the following should fix it.
componentWillUnmount() {
    this.endTween();
}

**Comment by mchl-hub** [comment]
Hello, unfortunately this commit does not solve the issue in my case.
I think you should change line 119 like this:
`this.tweenHandle = raf(this.tweenValue.bind(this));`

Then `tweenHandle` always contains the latest `raf` handler and `raf.cancel` works as desired.
