### ISSUE TITLE
Again: "Warning: setState(...): Can only update a mounted or mounting component."

### ISSUE THREAD

**Issue by mchl-hub** [ameyms/react-animated-number#3]
I found same problem as #2 but your commit did not solve the issue in my case.
I think you should change line 119 like this:
`this.tweenHandle = raf(this.tweenValue.bind(this));`

Then `tweenHandle` always contains the latest `raf` handler and `raf.cancel` works as desired.

**Comment by ameyms** [comment]
Thanks for reporting. I will push an update tomorrow

**Comment by ameyms** [comment]
Hmm. So although I did not change anything related to this, I am not seeing this error anymore. Can you try once again with the latest version ([0.4.2](https://www.npmjs.com/package/react-animated-number))?

**Comment by ameyms** [comment]
I am closing this. Feel free to reopen if the issue still exists.
