### ISSUE TITLE
request feature: frameClassName

### ISSUE THREAD

**Issue by septs** [ameyms/react-animated-number#8]
https://github.com/ameyms/react-animated-number#framestyle-perc-number--object--void of the **className** version

I would like to add a **currentValue** parameter, because my application is not based on the **percentage**

**Comment by ameyms** [comment]
@septs Just so that you are unblocked in case you are waiting on this, you can always calculate current value using:

`finalValue * 100 /  perc`

**Comment by septs** [comment]
@ameyms accuracy problem
